version: "3.9"

services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
      target: etl
    volumes:
      - $HOME/.config/gcloud:/root/.config/gcloud:ro
    environment:
      TABLE_NAME: ${TABLE_NAME}
      DATASET: ${DATASET}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}


